services:
  postgres:
    platform: linux/amd64
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    container_name: postgres_db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - mystack-postgres-data:/var/lib/postgresql/data
      # - ./services/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mystack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    env_file: .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME:-n8n}
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_RUNNERS_ENABLED=true
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - GENERIC_TIMEZONE=${TIMEZONE:-America/New_York}
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - mystack-n8n-data:/home/node/.n8n
    networks:
      - mystack-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


volumes:
  mystack-postgres-data:
  mystack-n8n-data:

networks:
  mystack-network:
    driver: bridge
