services:
  postgres:
    platform: linux/amd64
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    container_name: postgres_db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - mystack-postgres-data:/var/lib/postgresql/data
      # - ./services/postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mystack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mystack-postgres-data:

networks:
  mystack-network:
    driver: bridge
